debug = false
current_chain = "sepolia"

[server]
port = "9090"
host = "localhost"
prefix = "app"

[log]
level = "info"

[default_chain]
chain = "Sepolia"
currency = "native"

[chains.sepolia]
url = "https://sepolia.infura.io/v3/"

[chains.goerli]
url = "https://goerli.infura.io/v3/"
