debug = false
current_chain = "sepolia"
account_owner = "0x99e6fE79F94a3744089a1b3982D425406Ad4c55c"

[server]
port = "9090"
host = "localhost"
prefix = "app"

[log]
level = "info"

[default_chain]
chain = "Sepolia"
currency = "native"

[database]
file = "toad.db"

[chains.sepolia]
url = "https://sepolia.infura.io/v3/"
simple_account_factory_address = "0xB6C7963d2aB527b79842214160683f953bD8998b"
usdc_address = "0xFa38B962562DF7F9eeD9d8Db3cC261053EFC263B"
currency = "SepoliaETH"

[chains.goerli]
url = "https://goerli.infura.io/v3/"
simple_account_factory_address = "0xB6C7963d2aB527b79842214160683f953bD8998b"
usdc_address = "0x07865c6e87b9f70255377e024ace6630c1eaa37f"
currency = "GoerliETH"
