[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
config = "0.13.3"
derive_more = "0.99.17"
dotenvy = "0.15.7"
env_logger = "0.10.0"
log = "0.4.14"
serde = "1.0.177"
